apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aguchomattar/argocd-gitops.git
    targetRevision: main
    path: charts/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-dev
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true