---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-creds
  namespace: hermes-project
spec:
  encryptedData:
    TELEGRAM_CHAT_ID: AgA55jDn9A/gxfvIVkDlUYnUJSdUxV61JHsiiOWv67UKHGlgxvnXuzM2Wo5qHDKSjQ2MO+pBTG393WCmDYW45U50eOBMd7ML2byb0T2ekLXn0QOpR7Viaau3l6VKmlkMrGEvR18FEiMxPQcb8tzA5+MCEWddmyjAQa/pTsa9kI4ip6U/0db0994hwwajZvIlyI1EMS2R77MI60P5U3VJr6hwx5MUiN5YtnKSk8HSE2yCgQykgUpubfnEWAOvAmjDziImArTy6x6IYjVwVDmUaAHALYYcLlQ+bz0/DEYfWxtBaGBzq8bm8ssxnjGoCQM9T7z/6c3OJOz7m9CPFsTUqYJSIjbp0fO+dThmYCCVsBRlY8QZlUd/C+w8KsYI8dtAxhqG5+T2HjLdDeuaBgwVle+yfyL0mIi+j7jHm9zEo9OvqnG0QJRJfSwjA6wrx2ZltOtMhqHXamxy7nRBdovBKwB10fy7jcJbpbId7+jKEGTt7wpeorGWiTTXPUWracRlqajo89EzeLmFA4cTOr+5hGlKVo8Hq2jL59M/8uh1nOe+SVugPZHJ/phSa8lWTVEUZXpP98EQY4VjoRVuPcLJtFhU9/s/KxWkbjBLlWtWta9LN1eAVw0kJnXasypnv5cEauXVjX43UfTN5uQuVFXrPPi3+UIWxULk9bj8Qo7Ckb1prbescbtgpPkISJ3oCEhK0TGAMGJ4iwz39iCD
    TELEGRAM_TOKEN: AgAMmSmb6PYHLxTweOzuG5dNywhQQoJ5hYJibIv82DtMb3ofdebRfQpklL50EGkokFsyq/8IHDc8UAW8CcebZ8Cy87dbIj1t3otTlwmEJEUsLyBwtAPsQcxwpl5nUhrNCmtPQABpFmM0eA8NXCxudfgYTosD7OQNiT+93etuQJBdW8GUXJt93CL2JwJv0cF2MrFbJvaQxG2tBRReD6xGHBlnq9Z1l4HuTqPUAXDxKAA4/95P4EPuyXM5FVf7VbXS8i2t03RAyGQtcuQrR++RrO45xbmXyIRW56TkeHg5yyz9gE61iDlqbaBsKsC4Ndwn08lWk9cvhHJ0IjCEM+Dp2zXSij0EmlBsCVfSWJGyL8OY71r5gG+3Uq+TfVkVDyxHJj1zjVaIGFILrTt9QNQos5K4mqbH8nNulx41gy6wv5CcMi0Qaih3sCUWiaEP+N/q4m+dIve7EN3BgzI0JvtqAtcDtpWaCkHqvcRZNBc7S5nHTNVdOjx3TZ/nhQGjFOkhzrd3DnfS0Mc1fbwe+jpmMaMMCyRPySuqAzbBK4rUxNe9JdDW80Ssw1QV+RcqeV35XL8vjGw7RpQacSuwHqdDeg0pZLORqkbCuxVOmXhXmJXS+8InpD8Xsqi0jYK03Ojn01JsyWkFZuWBZW0FwEtW4NwZkoHBM8zjLnJD25yx/pslDx9Xd9nhCw0+ATLN8P69xmzGakxagZyV8uc1gLzuzOVWnIavSzQQIG+vIUQc4/rPUDGkKxgTjjYY50gy15WN
  template:
    metadata:
      name: telegram-creds
      namespace: hermes-project
    type: Opaque
